### PR TITLE
Black Formatting (Take 2)

### LINKED ISSUE #222: Use black for formatting
Use black for formatting after #214, #215, #217, #218.

Add a pre-commit hook and instructions for how to activate it in the contributing guide.

### PR DESCRIPTION
**Pull request by richford**
Resolves #222 
Supersedes #223

### CODE REVIEW

**Comment by arokem** [comment]
LGTM! It seems that Black doesn't like your javascript-style indentation. I can't object to that 😄

**Comment by arokem** [comment]
Oops - sorry - I missed this: shouldn't black be a dev requirement?

**Comment by arokem** [comment]
And `pre-commit`?

**Comment by arokem** [comment]
Oh! Nevermind. I just needed to update my remotes to point `upstream` away from richford/cloudknot and to nrdg/cloudknot

**Comment by richford** [comment]
> LGTM! It seems that Black doesn't like your javascript-style indentation. I can't object to that 😄

But how else am I supposed to stay under the characters-per-line limit imposed by the punch card? 😄

**Pull request merged**
