### PR TITLE
Use moto for unit testing

### LINKED ISSUE #22: Use moto for unit testing,
maybe?

### PR DESCRIPTION
**Pull request by richford**
This PR is a rebased copy of #219. Reopening from my own fork to confirm that no AWS credentials are needed.

Resolves #22.

### CODE REVIEW

**Comment by richford** [comment]
Finally! @arokem this is ready for review.

**Comment by richford** [comment]
And I believe we can now remove the secrets from the github repo settings.

**Comment by arokem** [comment]
LGTM!

**Comment by arokem** [comment]
No more secrets!

**Pull request merged**
