### PR TITLE
Windows carriage return

### PR DESCRIPTION
**Pull request by arokem**
Also documents issues with pywin32.

### CODE REVIEW

**Comment by richford** [comment]
Thanks @arokem. That's a nice tidy fix! Looks like there's just a linting error. Can you run `black` and commit/push?

**Comment by arokem** [comment]
I think that the test errors have to do with the moto mocking. The reason I think that's the case is because I can run the code with no error outside of the moto mocking context.

@richford : is there a particular reason that you pinned a particular dev version of moto [here](https://github.com/nrdg/cloudknot/blob/master/setup.cfg)?

**Comment by richford** [comment]
I pinned it to that version to capture [one of my PRs to moto](https://github.com/spulec/moto/pull/3201), which resolved [this issue](https://github.com/spulec/moto/issues/3127). But we can pin to any version greater than that if needed.

**Comment by arokem** [comment]
Sadly, upgrading moto to the most recent version doesn't help anyway.

**Comment by arokem** [comment]
Looks like we're hitting [this](https://github.com/spulec/moto/issues/3530), but the suggested fix -- upgrading to a recent version of moto -- is not helping.

**Comment by arokem** [comment]
Even worse, this upgrade seems to cause some additional new failures.

**Comment by arokem** [comment]
OK - pinning responses to 0.12.0 and keeping the pin on moto seems like the magic combination for now, at least until that issue on moto is resolved. It would be great to merge this, if this is indeed ready, and put out a new release, as I expect some new users in early January.

**Comment by arokem** [comment]
Oh - BTW: I have verified that the fix for `\r` does work as intended with at least on Windows user, who had that issue.

**Pull request merged**
